apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-fritzbox-exporter
  labels:
    app: prometheus-fritzbox-exporter
  namespace: kube-prometheus-stack
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prometheus-fritzbox-exporter
  template:
    metadata:
      labels:
        app: prometheus-fritzbox-exporter
    spec:
      serviceAccountName: prometheus-fritzbox-exporter
      containers:
        - image: pdreker/fritz_exporter:2.6.1
          imagePullPolicy: Always
          name: prometheus-fritzbox-exporter
          env:
          - name: FRITZ_PORT
            value: "9100"
          - name: FRITZ_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: prometheus-fritzbox-exporter
                key: FRITZ_HOSTNAME
          - name: FRITZ_USERNAME
            valueFrom:
              secretKeyRef:
                name: prometheus-fritzbox-exporter
                key: FRITZ_USERNAME
          - name: FRITZ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prometheus-fritzbox-exporter
                key: FRITZ_PASSWORD
